### ISSUE TITLE
Rework build & release process

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#94]
- windows build (cx_freeze based, nsis) is currently not working for me.
 - automate on the cloud

Ideas to try / explore:
 - [x] migrate to pyInstaller (already in use for the mac build)
 - [x] travis automated build for ~linux and~ **osx**
 - [x] appveyor automated build for windows
 - [x] travis github release
 - [x] appveyor github release
 - [x] implement git flow like release process

**Comment by benjec83** [comment]
I can't really contribute with any coding/dev help but happy to send some $$ your way for your trouble/time - is the paypal option through Comicvine the best way?

**Comment by davide-romanini** [comment]
As of 1.2.1 I made the following changes:
 * macOS and windows releases are automatically built and uploaded from [Travis CI](https://travis-ci.org/davide-romanini/comictagger)
 * new features are generally developed on `feature branches` and submitted to `develop` via Pull Requests
 * all pull requests are built automatically to catch up errors early
 * new releases are made from `develop` creating a new tag `git tag -a X.Y.Z -m ''`
 * version numbers follow [SemVer](https://semver.org/)
 * `master` always points to latest release

Still missing:
 * Linux pyinstaller build is unusable
 * automatic tests
 * automatic pip release (should be easy with #138 and from Travis CI)

**Comment by WillPresley** [comment]
This is pretty amazing Davide, thanks for the update after so long. I will attempt to help with PRs when needed!

**Comment by davide-romanini** [comment]
I opened #148 #149 #150 for the pending issues. Time to close this one :-)
